trigger:
  - develop

variables:
  - name: registryName
    value: 'acrsharediepdev'
  - name: imageName
    value: 'gencat-iep-issuer-user-registry'                                            #Name Convention que se establezca
  - name: azureSubscription
    value: 'service-endpoint-bs-tf-deploy-apps-iep-dev'
  - name: containerServiceName
    value: 'aca-cross-keycloak-ms-iep-dev'                                       #El que toque respecto al AppService definido
  - name: resourceGroupName
    value: 'rg-cross-iep-dev'

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureCLI@2
    displayName: AZ ACR Login
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az acr login --name $(registryName)'
  - task: AzureCLI@2
    displayName: AZ ACR Build
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az acr build -t $(imageName):$(Build.BuildId) -t $(imageName):$(Build.BuildId) -r $(registryName) -f Dockerfile .'
      useGlobalConfig: true
      workingDirectory: '$(Build.SourcesDirectory)'
  - task: AzureContainerApps@1
    displayName: Deploy to Azure Container App
    inputs:
      azureSubscription: '$(azureSubscription)'
      containerAppName: '$(containerServiceName)'
      resourceGroup: '$(resourceGroupName)'
      imageToDeploy: '$(registryName).azurecr.io/$(imageName):$(Build.BuildId)'